is_normalized: true
base_path:
  iot_data_root: ./data/iot_data
  geoJson_data_root: ./data/geoJson
config_normalization:
  normalization_script_base: ./Main.py
  normalization_script_path: ''
  is_normalized: true
config_datapath:
  geoJson_data: C:\Users\macma\PycharmProjects\HeatMap---TBDM2425\./data/geoJson
  iot_data: C:\Users\macma\PycharmProjects\HeatMap---TBDM2425\./data/iot_data
date_range:
  start: '2025-03-02 11:00:00'
  end: '2025-03-02 12:00:00'
room: nome_della_stanza
intervals:
  - 30
  - 60
